### PR TITLE
Refactor ZIO effect instances

### PR DESCRIPTION
**Pull request by cipriansofronia**

### CODE REVIEW

**Comment by sksamuel** [comment]
Let me know when you're happy for this to be merged.

**Comment by sksamuel** [comment]
Would appreciate a review on this too !

https://github.com/sksamuel/pulsar4s/pull/100

**Comment by cipriansofronia** [comment]
@sksamuel, should be ok now, thank you very much, please go ahead and merge it.

**Comment by sksamuel** [comment]
👍

**Pull request merged**
