### PR TITLE
fix issue #1907

### PR DESCRIPTION
**Pull request by brunoballekens**
Map the DynamicMapping.Dynamic to true (as defined https://www.elastic.co/guide/en/elasticsearch/reference/7.4/dynamic.html)

### CODE REVIEW

**Comment by brunoballekens** [comment]
fixes issue #1907

**Comment by sksamuel** [comment]
Thanks, build is failing though.

**Comment by brunoballekens** [comment]
My mistake, did not run tests on master

**Comment by sksamuel** [comment]
Can you apply the same to the other PR ?

**Comment by brunoballekens** [comment]
sure, doing it at the moment
however travis fails because it does not support java 8 ?

**Comment by sksamuel** [comment]
Oh ok that's fixed on master. I'll merge.

**Pull request merged**
