### PR TITLE
Respect IndexRequest.createOnly when used inside bulk through HTTP - for 5.6.x

### PR DESCRIPTION
**Pull request by lustefaniak**
Backport https://github.com/sksamuel/elastic4s/pull/1294

### CODE REVIEW

**Comment by lustefaniak** [comment]
@sksamuel Hey, can we get 5.6.x released sometime soon?

**Comment by sksamuel** [comment]
:+1:

**Comment by sksamuel** [comment]
Will do a release tonight. If I forget please feel free to ping me on here to remind me !!

**Comment by lustefaniak** [comment]
@sksamuel many thanks!

**Comment by sksamuel** [comment]
No problem :)

**Pull request merged**
