### PR TITLE
add BigInt support

### PR DESCRIPTION
**Pull request by dontgitit**
followup to https://github.com/sksamuel/elastic4s/pull/1747#issuecomment-498921794

Adds support for `BigInt`

### CODE REVIEW

**Comment by sksamuel** [comment]
:+1:

**Comment by chenweisomebody126** [comment]
👍

**Comment by dontgitit** [comment]
hey, i was curious if you'd be able to cut a release on the 6.x branch with these changes? if not... are there any incompatibilities on the 7.x branch?

**Comment by sksamuel** [comment]
7.x should work with 6.x if you just avoid using an 7.x only features.

**Pull request merged**
