### PR TITLE
elastic4s-http: Fixes handling or TermsOrder in TermsAggregationBuilder (5.4.x)

### PR DESCRIPTION
**Pull request by kutchar**

### CODE REVIEW

**Comment by kutchar** [comment]
5.4.10? ;)

**Comment by kutchar** [comment]
@sksamuel Can you publish this as 5.4.10?

**Comment by kutchar** [comment]
Any feedback on this?

**Comment by sksamuel** [comment]
Not near the computer I need to do a release at the moment.

**Comment by sksamuel** [comment]
Released.

**Comment by kutchar** [comment]
Thanks

**Pull request merged**
