### PR TITLE
[6.7.x] add include_type_name param

### PR DESCRIPTION
**Pull request by kimxogus**
In rolling update to es `6.8` to `7.x`, These parameters need to be set for 6.8 and 7.x compatibility.

### CODE REVIEW

**Comment by kimxogus** [comment]
Also fixed travis jdk install issue.
https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766/6

**Comment by sksamuel** [comment]
👍

**Comment by kimxogus** [comment]
Can you tell when this will be published?

**Comment by kimxogus** [comment]
@sksamuel Could you release 6.7.x or 6.8.x including this?

**Pull request merged**
