### PR TITLE
Adds pipeline support to bulk API

### PR DESCRIPTION
**Pull request by kpmeen**
This PR adds pipeline support to the bulk API through `BulkBuilderFn`.

### CODE REVIEW

**Comment by sksamuel** [comment]
:+1:

**Comment by kpmeen** [comment]
Thanks for merging this @sksamuel :-)
Do you have any plans for when the next release will be?

**Comment by sksamuel** [comment]
I was keeping master for the 7.0 release, but I might release it as 6.3 as 7.0 is taking a long time to arrive from elastic. If you want it immediately, might be worth doing the same PR on release/6.2.x

**Comment by kpmeen** [comment]
:+1: will do

**Pull request merged**
