### PR TITLE
Analysers in template

### PR DESCRIPTION
**Pull request by remcobeckers**
I noticed that analyzers defined in a template were not included in the JSON that was submitted by the HttpClient. I created a fix for that and, to be able to test it easily, also added a Show typeclass for the CreateIndexTemplateDefinition type.

### CODE REVIEW

**Comment by remcobeckers** [comment]
Looks like rebasing on master broke my fix again. I'll have a look later today. Also my fix for `matchJson` apparently started braking some other tests. I'll check this out too.

**Comment by sksamuel** [comment]
The tests are flaky on master. As long as it works locally I'll merge it.

**Comment by remcobeckers** [comment]
There were indeed a few regressions that I fixed now.

**Comment by sksamuel** [comment]
:+1:

**Pull request merged**
