### PR TITLE
Added stopwords_path functionality to the client

### PR DESCRIPTION
**Pull request by apanimesh061**
I have added the functionality that can enables the user to give a file of stop words as an input to the index analyzer/filter. The file is stored in a path relative to the `config` directory in `ES_HOME`.

### CODE REVIEW

**Comment by sksamuel** [comment]
I really want to merge this as its a good addition, but you need to fix things like changing the readme to point to your travis build, and setting the scala version back to 2.10.5. I also suggest you squash the commits into a single one.

**Comment by apanimesh061** [comment]
You mean I should make the scala version back to 2.11.6?
How do I squash all the commits to a single one?

**Comment by sksamuel** [comment]
git rebase -i HEAD~5 (to go back 5 commits for example).

**Comment by sksamuel** [comment]
Then force push.

**Comment by apanimesh061** [comment]
I did that but I see that since then my builds are failing. There was some
error in "git checkout". What could be the reason?

On Mon, Jun 8, 2015 at 5:00 PM, Stephen Samuel <notifications@github.com>
wrote:

> Then force push.
>
>
> On 8 June 2015 at 21:59, Stephen Samuel (Sam) <sam@sksamuel.com> wrote:
>
> > git rebase -i HEAD~5 (to go back 5 commits for example).
> >
> > On 8 June 2015 at 21:59, Animesh Pandey <notifications@github.com>
> wrote:
> >
> >> You mean I should make the scala version back to 2.11.6?
> >> How do I squash all the commits to a single one?
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/sksamuel/elastic4s/pull/319#issuecomment-110137509
> >.
> >>
> >
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sksamuel/elastic4s/pull/319#issuecomment-110137944>.
>



-- 
Thanks and regards,
Animesh Pandey
Graduate Student
Northeastern University
Boston, MA, USA

**Comment by apanimesh061** [comment]
Hi, is the source okay to be merged  now?

**Comment by sksamuel** [comment]
Yes great thanks.

**Comment by sksamuel** [comment]
Do you have the stoplist.txt ?

**Comment by apanimesh061** [comment]
Stoplist.txt is just for the testing purposes. The user can create any file and place it in config folder. I generally use [this](https://www.dropbox.com/s/gfrkgawa8in3y1p/stoplist.txt?dl=0) list. As per the code that I added a `stoplit.txt` is temporarily created with 5-6 stopwords and testing is done on those stopwords. When testing is done the file along with home and config folders are deleted.

**Comment by sksamuel** [comment]
I just noticed that :)

I get this locally when running the tests:

org.elasticsearch.transport.RemoteTransportException: [Rumiko
Fujikawa][inet[/192.168.1.98:9300]][indices:admin/create]
Caused by: org.elasticsearch.indices.IndexCreationException: [analyzer]
failed to create index
at
org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:338)
at
org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:371)
at
org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:374)
at
org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:188)
at
org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:158)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.env.FailedToResolveConfigException: Failed to
resolve config path [stoplist.txt], tried file path [stoplist.txt], path
file [/tmp/1710ed0e-87ee-4cb1-885b-a375aa88b08b/config/stoplist.txt], and
classpath
at org.elasticsearch.env.Environment.resolveConfig(Environment.java:242)
at org.elasticsearch.index.analysis.Analysis.getWordList(Analysis.java:230)
at org.elasticsearch.index.analysis.Analysis.parseWords(Analysis.java:165)
at
org.elasticsearch.index.analysis.Analysis.parseStopWords(Analysis.java:185)
at
org.elasticsearch.index.analysis.StopTokenFilterFactory.<init>(StopTokenFilterFactory.java:56)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

**Comment by apanimesh061** [comment]
I will have to run it again on my system as well. 
But I tested the build today itself it was working fine. This would only happen if the `config` directory was not made as I create the file `stoplist.txt` in that directory.

**Comment by sksamuel** [comment]
It might be something to do with 1.6.0 which was just released. Try doing a
pull, master contains the update to 1.6 as well as your code.

**Comment by apanimesh061** [comment]
I changed the version to 1.6.0 and rebuilt. Then I ran tests on `AnalyzerTest.scala` and all tests passed.

**Comment by sksamuel** [comment]
Can you try just building master as it stands ?

**Comment by apanimesh061** [comment]
I cloned the repository again, built the project on `intellij`. I got this error:
```
/home/cloudera/Documents/reale4s/elastic4s/elastic4s-examples/src/main/scala/com/sksamuel/elastic4s/examples/UpdateSqlDsl.scala
Error:(17, 38) could not find implicit value for parameter indexable: com.sksamuel.elastic4s.source.Indexable[UpdateSqlDsl.this.Document]
  update id "id" in "index" / "type" source somedoc
                                     ^
Error:(17, 38) not enough arguments for method source: (implicit indexable: com.sksamuel.elastic4s.source.Indexable[UpdateSqlDsl.this.Document])com.sksamuel.elastic4s.UpdateDefinition.
Unspecified value parameter indexable.
  update id "id" in "index" / "type" source somedoc
                                     ^
```

**Comment by sksamuel** [comment]
Just delete that file for now, I will fix that tomorrow.

**Comment by apanimesh061** [comment]
I deleted that and rebuilt --> `Compilation completed successfully with 67 warnings in 25s 475ms`. I got no error regarding `stoplist.txt` and also I re-ran the test file and all tests are passing there. I hope I am not missing something here?

**Comment by sksamuel** [comment]
Hmmm its not running for me (see the error) nor is it wokring on travis.

**Comment by apanimesh061** [comment]
I see that. The only reason I can think of is that stoplist.txt was not
written to the config directory. Can you try putting a check on whether the
file exists as soon as it written to the config directory?

On Thu, Jun 11, 2015 at 9:48 PM, Stephen Samuel <notifications@github.com>
wrote:

> Hmmm its not running for me (see the error) nor is it wokring on travis.
>
> On 12 June 2015 at 02:44, Animesh Pandey <notifications@github.com> wrote:
>
> > I deleted that and rebuilt --> Compilation completed successfully with 67
> > warnings in 25s 475ms. I got no error regarding stoplist.txt and also I
> > re-ran the test file and all tests are passing there. I hope I am not
> > missing something here?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/sksamuel/elastic4s/pull/319#issuecomment-111322136>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sksamuel/elastic4s/pull/319#issuecomment-111322720>.
>



-- 
Thanks and regards,
Animesh Pandey
Graduate Student
Northeastern University
Boston, MA, USA

**Comment by apanimesh061** [comment]
I think this might be a file access permission issue. Not sure though. I synced my fork with your repo. Even my travis build is failing because of that but local build is passing.

**Comment by apanimesh061** [comment]
Hey,
I found the issue. The issue was that the Local elastic search node was starting with `local` set to `false` due to which it always connected itself to its master and used to search for `stoplist.txt` in master node but actually the file was in the local node that we started earlier. I changed `local(false)` to `local(true)` in `ElasticClient.scala` and also removed `UpdateSqlDsl.scala` and reran the build with ES 1.6.0 and everything [worked](https://travis-ci.org/apanimesh061/elastic4s).

**Pull request merged**
