### PR TITLE
FuzzyQueryBodyFn use param transpositions in json serialization

### PR DESCRIPTION
**Pull request by vdamery**

### CODE REVIEW

**Comment by sksamuel** [comment]
Thanks for the PR. Can you check the tests that are failing?

**Comment by vdamery** [comment]
@sksamuel Of course.

In local, I've got errors without my updates : 
```
docker-compose up
sbt clean test
...
[info] Tests: succeeded 673, failed 1, canceled 0, ignored 9, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed tests:
[error] 	com.sksamuel.elastic4s.search.ScrollTest
[error] (tests / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 95 s (01:35), completed Jan 4, 2021 11:45:19 AM

sbt "testOnly com.sksamuel.elastic4s.search.ScrollTest"
...
- should return an error if the scroll id doesn't parse *** FAILED *** (45 milliseconds)
[info]   "[security]_exception" was not equal to "[illegal_argument]_exception" (ScrollTest.scala:80)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
[info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6982)
[info]   at com.sksamuel.elastic4s.search.ScrollTest.$anonfun$new$9(ScrollTest.scala:80)

```
It seems that the remotes test fails due to security exceptions too. 
Do you have any ideas to help me fix the tests ?

**Comment by sksamuel** [comment]
It must be something related to the environment. It fails for you, passes in master, fails here, passes for me. I will disable the tests, they are low value tests anyway.

**Comment by sksamuel** [comment]
7.10.2 released

**Pull request merged**
