### PR TITLE
Feature/elastic4s-aws module

### PR DESCRIPTION
**Pull request by saraiva132**
Hey @sksamuel , as promised here is the PR addressing issue https://github.com/sksamuel/elastic4s/issues/749

I still have some concerns (I could not pull host header value from apache Http Request) but from my experience ElasticClient already fills that. Any edge case that I did not consider either in code or tests is of course more than welcome to be referred.

Feedback is appreciated :)

### CODE REVIEW

**Comment by dmjb** [comment]
Curious about the status of this PR... if any help is needed with testing/implementation, I'd be glad to provide some :)

**Comment by saraiva132** [comment]
@sksamuel When do you think you have the time to review this PR? Tell me if you still want to add it to elastic4s :)

**Comment by sksamuel** [comment]
Lovely, all merged :)

**Comment by MatteCarra** [comment]
@saraiva132 Thank you very much for your contribution.
It would be great if you could provide some usage examples.
I may have done something wrong but I'm facing 

> com.sksamuel.elastic4s.http.JavaClientExceptionWrapper: null

This is my code:
```
private class MySignedClientConfig(credentials: AWSCredentialsProvider, region: String) extends HttpClientConfigCallback {
  override def customizeHttpClient(httpClientBuilder: HttpAsyncClientBuilder): HttpAsyncClientBuilder = {
    httpClientBuilder.addInterceptorLast(new MyAws4HttpRequestInterceptor(credentials, region))
  }
}

private class MyAws4HttpRequestInterceptor(credentials: AWSCredentialsProvider, region: String) extends HttpRequestInterceptor {
  private val signer = new Aws4RequestSigner(credentials, region)

  override def process(request: HttpRequest, context: HttpContext): Unit = signer.withAws4Headers(request)
}
```

And then
```
private val uri = ElasticsearchClientUri(host, port)
HttpClient(uri, httpClientConfigCallback = new MySignedClientConfig(awsCredentials, region))

```

**Comment by uccmen** [comment]
How do I use this? I see no documentation on README or wherever.

**Pull request merged**
