### PR TITLE
implement isWriteIndex to AddAlias Action

### PR DESCRIPTION
**Pull request by kimxogus**
https://www.elastic.co/guide/en/elasticsearch/reference/6.5/indices-aliases.html#aliases-write-index

### CODE REVIEW

**Comment by kimxogus** [comment]
also fixed test failure

**Comment by sksamuel** [comment]
:+1:

**Comment by sksamuel** [comment]
Can we get this against master too ?

**Comment by kimxogus** [comment]
already done in #1705

**Comment by sksamuel** [comment]
Of course sorry. Thanks!

**Pull request merged**
