### PR TITLE
Add task support to DeleteByQuery in master

### PR DESCRIPTION
**Pull request by izzyreal**
We add `wait_for_completion` support to `Delete`.

The project I'm on is using 7.9. The same PR but to the `release/7.9.x` branch can be found here: https://github.com/sksamuel/elastic4s/pull/2472

Edit: **The below does not apply anymore** as per @sksamuel's comment below.

To not break the existing `Response` API, we don't touch `DeleteByQueryHandler`. Instead, to get the `taskId` of a `DeleteByQuery` that does not `wait_for_completion`, the consuming side can define a custom `DeleteByQueryHandler` and do the below:
```
def deleteUserByName(name: String) {
    implicit val handler: Handler[DeleteByQueryRequest, Either[DeleteByQueryResponse, CreateTaskResponse]] =
      DeleteByQueryHandlerWithTask
    client
      .execute {
        ElasticDsl.deleteIn("users").by(termQuery("name", name)).waitForCompletion(false)
      }
      ...
```

Special caution must be taken not to have the default `elastic4s` `DeleteByQueryHandler` implicitly in scope, for example:
```
import com.sksamuel.elastic4s.ElasticDsl.{ DeleteByQueryHandler => _, _ }
```

### CODE REVIEW

**Comment by sksamuel** [comment]
I replied in the other PR. I think for master I'm ok with us changing the response object.

**Comment by izzyreal** [comment]
* Changed the response in congruence with what is done in `ReindexHandlers`
* Fixed existing `DeleteByQueryTest`
* Added a test to make sure our new feature is working as intended
* Amended migration docs

Let me know if something's off about the styling/formatting. Also we could move `TaskRegex` into a shared place like `Handler.scala`.

**Comment by sksamuel** [comment]
TaskRegex could move yeah - if you wanted to make a PR I would merge.
I merged this one in since it was ready to go.

**Comment by izzyreal** [comment]
`TaskRegex` deduplication PR
https://github.com/sksamuel/elastic4s/pull/2491

**Pull request merged**
