### PR TITLE
Added ScriptType to Update DSL

### LINKED ISSUE #316: Not possible to use ScriptType.FILE
I can see in source that update script DSL only uses ScriptType.INLINE by default and there's no way to specify script type at all. I can create PR if you accept it ASAP and push new version to maven.

### PR DESCRIPTION
**Pull request by fuwaneko**
To resolve #316

### CODE REVIEW

**Comment by sksamuel** [comment]
Thanks

**Comment by fuwaneko** [comment]
@sksamuel NP, just accidentally stumbled upon it when converting old project from Java API.

**Comment by sksamuel** [comment]
You like the scala api?

**Comment by fuwaneko** [comment]
@sksamuel yes, it's easy to use and readable, thanks for good wrapper! Main points were scala futures and java api underneath. Other wrappers seem to be lazy and use inefficient REST api.

**Comment by sksamuel** [comment]
Cool.

**Comment by sksamuel** [comment]
1.5.13 will be on maven central in 20 minutes. Note, you need elastic4s-core_2.x not elastic4s_2.x if you were using < 1.5.12

**Comment by fuwaneko** [comment]
@sksamuel thanks a lot. I'm using 1.5.12, so no problems here :)

**Comment by fuwaneko** [comment]
@sksamuel hmm, 1.5.13 is still not available.

**Comment by sksamuel** [comment]
you're right, this is odd. I'll try again or bump it to 1.5.14

**Comment by sksamuel** [comment]
Ok I hadn't released it properly in nexus. Give it 15 minutes and it should
be there (won't appear in search.maven.org for 15 hours though).

**Comment by fuwaneko** [comment]
@sksamuel it works now, thanks.

**Pull request merged**
