### PR TITLE
Bump jackson to version 2.10

### PR DESCRIPTION
**Pull request by zettelmj**

### CODE REVIEW

**Comment by zettelmj** [comment]
Update the jackson dependencies to version 2.10

**Comment by pjfanning** [comment]
elastic4s 7.1 does not work with jackson 2.10 when it is compiled with jackson 2.9

**Comment by francisdb** [comment]
@sksamuel would you mind releasing a new version that contains this jackson upgrade?

We are migrating to scala 2.13 and a lot of dependencies have switched to jackson 2.10 (eg akka 2.6.x) which makes it impossible to use it together with elastic4s

For reference this is the error you get:
```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.9.9 requires Jackson Databind version >= 2.9.0 and < 2.10.0
	at com.fasterxml.jackson.module.scala.JacksonModule.setupModule(JacksonModule.scala:61)
	at com.fasterxml.jackson.module.scala.JacksonModule.setupModule$(JacksonModule.scala:46)
	at com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:17)
	at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:808)
	at com.sksamuel.elastic4s.json.JacksonSupport$.<clinit>(JacksonSupport.scala:12)
```

**Comment by fl-knix** [comment]
Would you mind cutting a release of `7.1.x` with this dependency upgrade? It would be greatly appreciated!

**Comment by sksamuel** [comment]
@fl-knix 7.1.x has been released as has 7.3.x

**Comment by kolemannix** [comment]
Thank you very much!

**Comment by shayangz** [comment]
@sksamuel can't find `7.1.x` beyond `7.1.0` on maven for Scala 2.11. Any chance `7.1.5` can be pushed for 2.11? https://search.maven.org/search?q=g:com.sksamuel.elastic4s%20AND%20a:elastic4s-core_2.11

**Pull request merged**
