### PR TITLE
Bump jackson to version 2.10

### PR DESCRIPTION
**Pull request by francisdb**
backport of #1928

### CODE REVIEW

**Comment by sksamuel** [comment]
Thanks.

**Comment by francisdb** [comment]
All thanks go to you @sksamuel !

**Comment by francisdb** [comment]
@sksamuel any chance we could get a release including this?

**Comment by francisdb** [comment]
Looks like play 2.7.4 also switched to jackson 2.10 (next to akka 2.6), a release would de-block us from upgrading those

**Comment by francisdb** [comment]
Are snapshots not deployed for 2.7.x?

**Comment by brunoballekens** [comment]
@sksamuel  Would it be possible to cut a release for 6.7 branch ? We are a bit blocked upgrading because of this.

**Comment by sksamuel** [comment]
6.7.4 has been released.

**Comment by francisdb** [comment]
Thank you! And may I wish you a happy 🎄 and 🎇

**Comment by lespea** [comment]
Do you have an eta for a 7.x release with updates to jackson + akka by chance?

**Comment by sksamuel** [comment]
I've been trying to publish 7.1.x for days, but I cannot get it to work.
I've even overhauled the build.sbt files.
Does anyone know why it would fail to publish ?

Errors like this:

[error] (clientakka / publishSigned) java.io.IOException: PUT operation to
URL
https://oss.sonatype.org/service/local/staging/deploy/maven2/elastic4s-client-akka/elastic4s-client-akka_2.13/7.1.4/elastic4s-client-akka_2.13-7.1.4.jar
failed with status code 400: Bad Request; Response Body: <html>
[error]   <head>
[error]     <title>400 - Bad Request</title>
[error]     <meta http-equiv="Content-Type" content="text/html;
charset=utf-8"/>
[error]
[error]

**Comment by sksamuel** [comment]
Never mind I sorted that out.
New releases for 7.1 and 7.3 are now released in maven.

**Pull request merged**
