### PR TITLE
Fix URL encoding of spaces

### PR DESCRIPTION
**Pull request by ievalu**
References https://github.com/sksamuel/elastic4s/issues/2352

I chose to just replace all plus signs with `%20`. Plus signs are encoded to `%2B` so this shouldn't break anything.

### CODE REVIEW

**Comment by sksamuel** [comment]
Good work thanks

**Comment by ievalu** [comment]
@sksamuel Could you release it?

**Comment by sksamuel** [comment]
I can do a 7.4 release yeah.

**Comment by sksamuel** [comment]
7.4.1 is out, takes ~hour to sync with central

**Comment by ievalu** [comment]
@sksamuel Hello once again, I've tried to use 7.4.1v in our project and it seems like it was released incorrectly, maybe you could check it out https://github.com/sksamuel/elastic4s/compare/v7.4.0...v7.4.1

**Pull request merged**
