### PR TITLE
Implement Slice API

### PR DESCRIPTION
**Pull request by polymorpher**
As discussed in https://github.com/sksamuel/elastic4s/issues/1027

Also implemented tests for that (manually checked, passing).

### CODE REVIEW

**Comment by sksamuel** [comment]
:+1:

**Comment by hensg** [comment]
:+1:

**Comment by hensg** [comment]
@sksamuel  Could you make a release for 5.4.x? I would like to use it too but I'm using ES 5.4

**Comment by sksamuel** [comment]
You would need to make a PR against 5.4.x branch if you want it for that version too.

**Comment by hensg** [comment]
@sksamuel  done https://github.com/sksamuel/elastic4s/pull/1113

**Pull request merged**
