### PR TITLE
add TypedResponseListener to streams (backport to 2.3.x)

### PR DESCRIPTION
**Pull request by rwiskerke**
(cherry picked from commit 875d74d)

### CODE REVIEW

**Comment by sksamuel** [comment]
:+1:

**Comment by rwiskerke** [comment]
@sksamuel Thanks for merging! Would very much like to have a release for 2.3.x, so I can get rid of my local snapshot dependency 👍

**Comment by sksamuel** [comment]
Released 2.3.2

**Comment by rwiskerke** [comment]
Thanks!

**Pull request merged**
