### PR TITLE
Clean up build.sbt

### PR DESCRIPTION
**Pull request by bbroeksema**
Most lucene requirements are not needed and joda-time is actually
required for compiling core. This was actually required to make the
project build from scratch.

### CODE REVIEW

**Comment by sksamuel** [comment]
The lucene requirements are needed for gradle builds.

**Comment by bbroeksema** [comment]
right. could you tell me how i can test that? I'm using sbt mainly. I'm fine with further improving the patch as long as I know how to test.

I guess we aggree that core is the proper place for the requirements?

**Comment by sksamuel** [comment]
Well you'd need to setup a gradle project, and include it. You can't remove them because like I said, the transitivity doesn't work for gradle for some reason. I'm happy if you know a workaround.

However, what I'd really recommend is you upgrade to the HTTP client because in v6 onwards, there's no dependency on elasticsearch core at all.

**Comment by bbroeksema** [comment]
re workaround: stop using gradle?! ;). Anyway, master is building for me, I'll close this pr.

**Pull request closed without merging**
