### PR TITLE
Add optional dependencies to core

### PR DESCRIPTION
**Pull request by solicode**
Potential fix for #754

Also, I removed a bunch of dependency declarations that seemed unnecessary to me since they get pulled in transitively. If there's a reason for those though, let me know.

### CODE REVIEW

**Comment by solicode** [comment]
I made a mess here with the commits. Let me get back to this later and clean it up.

**Comment by solicode** [comment]
Alright, I cleaned up the history.

**Comment by sksamuel** [comment]
There was some issue with log4j 2.7 which meant only 2.6.2 worked with elastic. Might have been fixed now mind.

**Comment by sksamuel** [comment]
https://discuss.elastic.co/t/issue-with-elastic-search-5-0-0-noclassdeffounderror-org-apache-logging-log4j-logger/64262/4

**Comment by solicode** [comment]
Ah, sorry, I didn't know about that. Haven't seen that problem myself. I was trying to match the version with the transitive dependency. Anyway, I reverted back to 2.6.2.

**Comment by sksamuel** [comment]
Looks good now.

**Pull request merged**
