### PR TITLE
Add support for IpField at ElasticFieldBuilderFn

### LINKED ISSUE #2389: IpField MatchError v7.12.0
When I gonna use ip field I see the follow match error:

`scala.MatchError: IpField(ip,None,List(),None,None,List(),None) (of class com.sksamuel.elastic4s.fields.IpField)
[info]   at com.sksamuel.elastic4s.fields.builders.ElasticFieldBuilderFn$.apply(ElasticFieldBuilderFn.scala:8)
[info]   at com.sksamuel.elastic4s.fields.builders.ObjectFieldBuilderFn$.$anonfun$build$3(ObjectFieldBuilderFn.scala:18)
[info]   at scala.collection.immutable.List.foreach(List.scala:333)
[info]   at com.sksamuel.elastic4s.fields.builders.ObjectFieldBuilderFn$.build(ObjectFieldBuilderFn.scala:17)
[info]   at com.sksamuel.elastic4s.fields.builders.ElasticFieldBuilderFn$.apply(ElasticFieldBuilderFn.scala:27)
[info]   at com.sksamuel.elastic4s.requests.mappings.MappingBuilderFn$.$anonfun$build$12(MappingBuilderFn.scala:80)
[info]   at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
[info]   at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
[info]   at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
[info]   at com.sksamuel.elastic4s.requests.mappings.MappingBuilderFn$.build(MappingBuilderFn.scala:79)`

It's happening because file `com.sksamuel.elastic4s.fields.builders.ElasticFieldBuilderFn` doesn't contain the case for IpField.

### PR DESCRIPTION
**Pull request by narma**
Fixes #2389

Also:
- Add `ignoreMalformed` and `nullValue` options to IpField regarding https://www.elastic.co/guide/en/elasticsearch/reference/7.12/ip.html

I want this hotfix for the 7.12 release branch but  I didn't find branch `release/7.12.x` so I make PR against `release/7.11.x`. Please specify a valid base branch in case I missed it.

### CODE REVIEW

**Comment by sksamuel** [comment]
Thanks, I will make a 7.12 branch.

**Comment by sksamuel** [comment]
Right now, master is still the 7.12 dev branch.

**Comment by narma** [comment]
Oh, I see, so #2389 is already fixed by current 7.12.1 release. I close this one then. Thanks!

**Comment by narma** [comment]
Waiting for 7.12.1 on maven central :)

**Comment by acteek** [comment]
For the current release, you can use IpRange  with /32 mask field type instead, it looks like "192.168.0.1/32"

**Pull request closed without merging**
