### PR TITLE
Add custom backwards compatible deserializer for Total

### PR DESCRIPTION
**Pull request by easel**
- Allows reading a number as produced by es6 vs the object produced by es7

### CODE REVIEW

**Comment by easel** [comment]
This one is a little tough to test, unfortunately. The existing tests still pass, but getting the entire es7 compatible test suite to pass against es6 and automating it is pretty tricky. Ideas welcome.

**Comment by easel** [comment]
Just as a point of order, I've compiled and deployed this to a couple of applications with both elastic6 and elastic7 and it nominally works.

**Comment by sksamuel** [comment]
I like the approach. Thank you for the pr.

**Comment by easel** [comment]
Thanks for the merge!

**Pull request merged**
