### PR TITLE
Separate HTTP request marshallers from executables

### PR DESCRIPTION
**Pull request by catalin-ursachi**
Addresses comment https://github.com/sksamuel/elastic4s/pull/1185#discussion_r158583449 in #1185

### CODE REVIEW

**Comment by catalin-ursachi** [comment]
I've called them "Marshallers" rather than "Builders" so I could call the result `MarshalledRequest` (but I suppose `BuiltRequest` or simply `Request` would also work, if you prefer either of those).

**Comment by sksamuel** [comment]
I've taken this and incorporated it into master as part of a larger change. Now `show` will include endpoint, method and parameters.

**Comment by catalin-ursachi** [comment]
Ah, great. I suppose this and #1185 can be closed, then?

**Comment by sksamuel** [comment]
Assuming I've not missed anything out you'd like to see.

**Comment by catalin-ursachi** [comment]
No, all looks good to me! 🙂 

Only suggestion I'd have is renaming the method:

```handler.requestHander(t: T): ElasticRequest```

since it doesn't return a handler, but a marshalled request. Maybe `handleRequest`, `buildRequest`, or `marshalRequest` would be clearer?

**Comment by sksamuel** [comment]
Yes good point.

**Pull request closed without merging**
