### PR TITLE
support versioning in bulk index

### PR DESCRIPTION
**Pull request by yanns**
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html#bulk-versioning

### CODE REVIEW

**Comment by sksamuel** [comment]
:+1:

**Comment by yanns** [comment]
@sksamuel do you have a rough idea when you will push a new version?
(just asking - no pressure)

**Comment by sksamuel** [comment]
This week for the 6.0 release. Before thanksgiving on Thurs.

**Comment by yanns** [comment]
@sksamuel sorry for up-ing this but I don't see any new version in the meantime. Can we help you somehow for that?

**Comment by sksamuel** [comment]
Yes delayed because I am struggling to decide on this:

In an API, when dealing with Future's, for a case where you have three types of things:

1. The success case
2. The system dealt with your request but returned an error, like say "invalid search term" or something
3. An error like host not found, connection timeout etc.

Do you think it's better to have:

`Future[Either[RequestSuccess, RequestFailure]]` and then have case 3 above as the `Exception` case of a Future.
This means you have to pattern match on the success case.

Or

`Future[RequestSuccess]` and then model case 2 above in the form of an Exception which is a subtype of `Exception` (case 3). This means when handling errors you pattern match on the error case.

Or

Third way.

**Comment by yanns** [comment]
@I'll discuss that with @jadlr who is also using the lib quite intensively, and we get back to you.
Do you want to discuss that on this PR, or do you prefer that we open an issue for that?

**Comment by sksamuel** [comment]
Can do it on email, or an issue or here I don't mind. It's really the last thing I want to get done before I release, and will only take a day once I decide. I've just been flip flopping between ideas, and I want to get it right before I cement in place 6.0. Especially as this is the time the rest of TCP users will finally move to the HTTP api.

**Comment by yanns** [comment]
@sksamuel With @jadlr, we'd prefer the following approach:
`Future[Either[RequestFailure, RequestSuccess]]` (failure on the left, success on the right)

- `Future[Right[A]]` is the success case (ex: elasticsearch answers with 200, 201...) (the 1st case)
- `Future[Left[RequestFailure]]` is the expected failure case (ex: elasticsearch answers with 400)  (the 2nd case)
- `Future.failure` is the unexpected failure (connection problem, 503 errors).  (the 3rd case)

In both failure cases, it's important that the client has all possible information to be able to react.
For ex, we can retry with a backoff in case of 503.

**Comment by sksamuel** [comment]
What I did last night and is in master (but happy to change it round again) was this:

`Future[Response[U]]` where Response is a sealed trait of `RequestSuccess[U]` and `RequestFailure` and `Future.failure` is the unexpected failure.

The `Response` object comes with status code, full json body, all http headers.

**Comment by yanns** [comment]
I look at master. At first sight, I think you forgot to make `Response` a sealed trait (it's a normal trait)

Some arguments to favor `Either` instead of the sealed trait:
- we have more and more tools to work with `Either` in the scala community. For example, cats have an Either transformer that makes it easy to compose different `Future[Either[E, _]]`.
- In the `Response` you are implementing `map`, `fold`, `foreach` that are already implemented in `Either`:
```
val e: Either[String, Int] = Right(42)
e.fold(identity, _.toString)

import cats.syntax.either._
e.map(_ + 2)
e.foreach(println)
```

But the sealed trait is not a big issue. We can still transform it to an `Either` if needed.
Actually, if you want to go with the sealed trait, you could add:
```
sealed trait Response[+U] {
  def toEither: Either[RequestFailure, RequestSuccess[U]]
}
```

**Comment by sksamuel** [comment]
Good feedback. My rationale for using a sealed trait (I will seal it :)) instead of an Either is that I was sick of typing out Either[RequestFailure, X] everywhere :)
I could just make a type alias. Maybe I'll change it back to Either now and then get this release out.

**Comment by sksamuel** [comment]
If HttpClient returns `Future[Either[RequestFailure, RequestSuccess[U]]]` then I think we get the best of all worlds. An either for easy interop with existing scala tools, and the types that contain status, body, and headers.

**Comment by yanns** [comment]
When I use a lot of `Either[E, _]` where `E` is fixed, I usually introduce a type alias.

Another notice:
```
def get: U // returns the marshalled response U or throws an exception
```

Maybe you could add a method returning an Either[ParseError, U], and makes `get`using it:
```
def deserialize: Either[ParseError, U]
def get: U = deserialize.fold(e ⇒ throw new Exception(e), identity)
```
So that clients can decide which level of "FP purines" they want.

**Comment by yanns** [comment]
> If HttpClient returns Future[Either[RequestFailure, RequestSuccess[U]]] then I think we get the best of all worlds. An either for easy interop with existing scala tools, and the types that contain status, body, and headers.

👍

**Comment by sksamuel** [comment]
It's done, I just need to update the tests. Then I will do the 6.0 release.

**Comment by yanns** [comment]
you're awesome, thx!!!

**Comment by jadlr** [comment]
Thanks @sksamuel! Looking forward to the release

**Pull request merged**
