### PR TITLE
Add `scroll` to ReindexRequest

### PR DESCRIPTION
**Pull request by danslapman**
As documented [here](https://www.elastic.co/guide/en/elasticsearch/reference/7.9/docs-reindex.html#docs-reindex-api-query-params)

### CODE REVIEW

**Comment by sksamuel** [comment]
👍🏼

**Comment by sksamuel** [comment]
Can we make the same PR to master too ?

**Comment by danslapman** [comment]
Sure! #2296

**Comment by sksamuel** [comment]
Awesome thank you.

**Pull request merged**
