### PR TITLE
UpdateDsl: Added update(source), doc(source) methods

### PR DESCRIPTION
**Pull request by shanielh**
I need those methods because I build the document on my own, Because I've got issues with the `FieldMapper`.

Hope you'll merge it,
Thanks.

### CODE REVIEW

**Comment by sksamuel** [comment]
:+1:

**Comment by shanielh** [comment]
Thanks! Is there a snapshot version that I can work with until a new version is released?

**Comment by sksamuel** [comment]
I'll put out 2.2.0 later tonight, as 2.2 has just been released.
I'll do 2.1.x too

**Comment by shanielh** [comment]
Thanks @sksamuel , Fastest merge ever :smiley:

**Comment by sksamuel** [comment]
:)

**Comment by sksamuel** [comment]
2.2.0 released

**Comment by sksamuel** [comment]
2.1.2 released

**Pull request merged**
