### PR TITLE
Fix 1085: handle 200 response status code when indexing

### PR DESCRIPTION
**Pull request by yanns**
When indexing an existing document (with the same id), elastic search
answers with a 200 response status.

fix https://github.com/sksamuel/elastic4s/issues/1085

### CODE REVIEW

**Comment by sksamuel** [comment]
Can you add a test so I don't get caught out again. Can be added to the existing index test suite.

**Comment by yanns** [comment]
Yes, I tried to do that, but have not really found an existing test that would fit this change.

Do you have any pointer of existing tests I could use as a "template"?

**Comment by sksamuel** [comment]
com.sksamuel.elastic4s.indexes.IndexTest

All you need to do is add another that indexes the same document twice I think ? First time it will be 201 second time 200.

**Comment by yanns** [comment]
Thx for the pointer!

I added a test: https://github.com/sksamuel/elastic4s/pull/1086/commits/0362f6626204ebeab0e6fd6b5d52442729c40f34

Do you prefer several commits? Or a rebase?

**Comment by sksamuel** [comment]
Perfect I'll merge once green.

**Pull request merged**
