### PR TITLE
Polygon multiple holes support

### LINKED ISSUE #1427: Polygon with multiple holes
Polygon shape should support multiple holes. Currently only one.

### PR DESCRIPTION
**Pull request by kraanerk**
This fixes #1427

### CODE REVIEW

**Comment by sksamuel** [comment]
Awesome, can we have an overloaded apply method in a companion object that allows just a single sequence as before.

**Comment by kraanerk** [comment]
Seems this is not possible.
```
  object Polygon {
    def apply(points: Seq[GeoPoint], hole: Option[Seq[GeoPoint]]) =
      new Polygon(points, hole.map(Seq(_)))
  }
```
does not compile:
```
Error:(8, 14) double definition:
def apply(points: Seq[com.sksamuel.elastic4s.searches.GeoPoint],hole: Option[Seq[com.sksamuel.elastic4s.searches.GeoPoint]]): com.sksamuel.elastic4s.searches.queries.geo.Shapes.Polygon at line 11 and
case def apply(points: Seq[com.sksamuel.elastic4s.searches.GeoPoint],holes: Option[Seq[Seq[com.sksamuel.elastic4s.searches.GeoPoint]]]): com.sksamuel.elastic4s.searches.queries.geo.Shapes.Polygon at line 8
have same type after erasure: (points: Seq, hole: Option)com.sksamuel.elastic4s.searches.queries.geo.Shapes.Polygon
  case class Polygon(points: Seq[GeoPoint], holes: Option[Seq[Seq[GeoPoint]]])
```

**Comment by sksamuel** [comment]
Hmm yeah they both erasure to Seq[_].

**Comment by kraanerk** [comment]
This compiles:
```
  object Polygon {
    def apply(points: Seq[GeoPoint], hole: Seq[GeoPoint]) =
      new Polygon(points, Some(Seq(hole)))
  }
```

**Comment by sksamuel** [comment]
I think the breaking change is ok - plenty of other breaking changes in master.

**Pull request merged**
