### PR TITLE
Url parameter

### PR DESCRIPTION
**Pull request by kimxogus**
- Fix `ReindexContextBuilder`
- Added `AbstractURLParameterDefinition` for url parameters in `HttpClient` request.
- Added `asyncTimeout` to set timeout for async request.

### CODE REVIEW

**Comment by sksamuel** [comment]
Great PR, what about making AbstractURLParameterDefinition a case class, and just having it as a field in any of the requests that need it?

**Comment by kimxogus** [comment]
Well, as I know, extending case class is not possible.
I added BaseURLParameterDefinition case class instead.

**Comment by sksamuel** [comment]
I mean like have the case class

`case class UrlParameters`

and then in each request

`case class SearchRequest(index:String, ....., urlParams: UrlParameters, ....)`

**Comment by kimxogus** [comment]
Ah, that makes sense.
Looks good. I'll change it to use case class.

**Comment by sksamuel** [comment]
Then you don't need to define the fields in each request.

**Comment by sksamuel** [comment]
We'll still need the .timeout() .refresh() methods etc, which will just do .copy(url = url.copy(...))

**Comment by kimxogus** [comment]
Changes applied.

**Comment by sksamuel** [comment]
I think it looks great but one more change :)
I don't think the url parameters itself needs to be Optional, because all the values inside it are optional.

**Comment by kimxogus** [comment]
Updated as requested :)

**Comment by sksamuel** [comment]
Awesome.

**Pull request merged**
