### PR TITLE
Fix broken termsQuery when empty seq is passed

### PR DESCRIPTION
**Pull request by grillorafael**
Is a PR like this that you suggested?

#1338

### CODE REVIEW

**Comment by sksamuel** [comment]
Maven central is being slow atm, I'll keep trying to release but it might be tomorrow.

**Comment by grillorafael** [comment]
I just updated the PR disabling travis at the same time you merged. Please make sure this is a valid change!

**Comment by sksamuel** [comment]
Yep.

**Comment by grillorafael** [comment]
Thanks! Tomorrow would be just fine if you can't today. And thanks for the fast feedback as usual

**Pull request merged**
