### PR TITLE
Update cats-effect to 3.0.0

### PR DESCRIPTION
**Pull request by rkrzewski**
Cats-effect 3.0.0 release is coming up soon, so I thought a PR updating that dependency might be in order.

The ecosystem will OSS library ecosystem will probably upgrade quickly, but applications may lag behind for a while, so maybe creating a separate `elastic4s-effects-cats-2` module for providing compatibility with legacy cats-effect 2.x would be a good idea. Please let me know.

### CODE REVIEW

**Comment by rkrzewski** [comment]
```
[info] *** 1 TEST FAILED ***
[info] DateRangeQueryHttpTest:
[info] a range query should 
[info] - support date math for gte *** FAILED ***
[info]   1 was not equal to 2 (DateRangeQueryHttpTest.scala:47)
```
Seems unrelated?

**Comment by sksamuel** [comment]
I think the idea of having two modules is best.

**Comment by sksamuel** [comment]
> ```
> [info] *** 1 TEST FAILED ***
> [info] DateRangeQueryHttpTest:
> [info] a range query should 
> [info] - support date math for gte *** FAILED ***
> [info]   1 was not equal to 2 (DateRangeQueryHttpTest.scala:47)
> ```
> 
> Seems unrelated?

Yep, I will fix this, not related to anything.

**Comment by sksamuel** [comment]
If you want to move out of draft I will merge.

**Comment by rkrzewski** [comment]
Cats-effect 3.0.0 final is planned for Sunday, 28th. I think it's reasonable to wait util then with merging.

**Comment by sksamuel** [comment]
Sounds good.

**Comment by rkrzewski** [comment]
oops, I've added some some vscode and Metals files accidentally. Let me clean that up

**Comment by rkrzewski** [comment]
OK, it's ready to merge.

**Comment by sksamuel** [comment]
I'll cut a 7.12 release with this later today.

**Pull request merged**
