### PR TITLE
Let ParentIdQueryDefinition extend QueryDefinition

### PR DESCRIPTION
**Pull request by douglaz**

### CODE REVIEW

**Comment by sksamuel** [comment]
:+1:

**Comment by kutchar** [comment]
@sksamuel are there any plans of backporting this to 5.x series?

**Comment by sksamuel** [comment]
Why not eh ?

**Comment by sksamuel** [comment]
5.4.7 has this fix applied.

**Comment by kutchar** [comment]
Thanks

**Comment by sksamuel** [comment]
It's there. Just doesn't appear in some searches for a while.
http://central.maven.org/maven2/com/sksamuel/elastic4s/elastic4s-core_2.11/5.4.7/

**Comment by kutchar** [comment]
I see. Thank you.

**Comment by sksamuel** [comment]
If you add it to your build it'll work.

**Pull request merged**
