### PR TITLE
add parent aggregation support

### PR DESCRIPTION
**Pull request by StyopinN**
Add parent aggregation support.

Details: https://www.elastic.co/guide/en/elasticsearch/reference/6.7/search-aggregations-bucket-parent-aggregation.html

### CODE REVIEW

**Comment by sksamuel** [comment]
:+1:

**Comment by StyopinN** [comment]
When do you plan to release build with this fix?

**Comment by sksamuel** [comment]
6.7.8 just released.

**Comment by StyopinN** [comment]
Great news! Thanks!

**Pull request merged**
