### PR TITLE
Add filtered knn search

### PR DESCRIPTION
**Pull request by tlandelin**
Added the filter option for KNN search documented [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/knn-search.html#knn-search-filter-example).

Also, created some builder methods on the KNN case class.

This PR resolves https://github.com/sksamuel/elastic4s/issues/2903

### CODE REVIEW

**Review by sksamuel — APPROVED** [review]

**Comment by sksamuel** [comment]
Thanks!

**Comment by tlandelin** [comment]
Could you release a new version so we can access the change in maven?

**Comment by xiaofeiXM** [comment]
> Could you release a new version so we can access the change in maven?

@sksamuel can you please help us with this? thanks!

**Comment by sksamuel** [comment]
Yep, sonatype has been down for a few days, so once it's back I will release.

**Comment by tlandelin** [comment]
Any luck with sonatype coming back up?

**Comment by sksamuel** [comment]
Yep 8.9.2 has been released.

**Comment by tlandelin** [comment]
Awesome, thanks!

**Pull request merged**
