### PR TITLE
#565 create index from raw json string also with Http Client

### PR DESCRIPTION
**Pull request by mstockerl**
The suggested solution in this ticket does not work with the Http Client

### CODE REVIEW

**Comment by mstockerl** [comment]
Also added SubAggregation support in TermsAggregation

**Comment by sksamuel** [comment]
Can terms have sub aggregations?

**Comment by mstockerl** [comment]
Yes, it is a bucket aggregation. 
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html

**Comment by sksamuel** [comment]
Ah yeah of course. Should probably do the metadata fields too.

**Pull request merged**
