### PR TITLE
Search Type

### PR DESCRIPTION
**Pull request by bursalihilal**
Search types are added

### CODE REVIEW

**Comment by sksamuel** [comment]
:+1:

**Comment by bursalihilal** [comment]
Could you add this to tags/5.5.2 . I need to use 5.5.2 version.

**Comment by sksamuel** [comment]
I can release another 5.5.x release, it won't be 5.5.2 as you can't change versions once released.

**Comment by bursalihilal** [comment]
Which version will you do that and when could you do that? We have in a hurry a little.

**Comment by bursalihilal** [comment]
I could not this version on Maven. Could you make it ?

**Comment by sksamuel** [comment]
5.5.7 is on maven central now.

**Comment by bursalihilal** [comment]
Thank you.

**Pull request merged**
