### PR TITLE
1100 span near produces span or query (copy from 5.4 branch)

### PR DESCRIPTION
**Pull request by unkarjedy**
Copy of pull request-1101 (was merged into 5.4)
https://github.com/sksamuel/elastic4s/pull/1101

### CODE REVIEW

**Comment by sksamuel** [comment]
This is bringing in the all_fields change as well as the span change.

**Comment by unkarjedy** [comment]
@sksamuel  Sorry... Fixed. 
Could you please suggest me how to apply this fix to all release branches automatically?
Or at least semi-automatically?

**Comment by sksamuel** [comment]
The closest you will get is `git cherry-pick`, are you familiar with that?

**Comment by unkarjedy** [comment]
@sksamuel 
Yes, that is the way I do it right now... 
Actually, I am quite good at Git, but I have little experience with its Web wrappers like GitHub. 
I thought that maybe there are some tools to auto-create several pull-requests.
I think my time has come and I should create such tool =D

**Comment by sksamuel** [comment]
Yes could be a github plugin.

**Comment by sksamuel** [comment]
Thanks for the PR. Can you explain this rawArray method to me, I didn't understand why you added it.

**Comment by unkarjedy** [comment]
@sksamuel  
For some reason, `XContentBuilder` did not write a comma after each clause object bytes was added with `writeRaw` method. I've spent enough time reverse-engineering XContentBuilder and did not find the `normal` way to fix it. As a workaround, I collect all the raw values in one buffer and insert comma byte between them. After that, I write one big raw value as raw array value.

As I understood you have replaced elsticsearch `XContentBuilder` with your own implementation in version 6.x. And there is no such bug there.

**Comment by sksamuel** [comment]
Oh it's in a bug in 'their' version. Ok that's why I was confused, I thought it was a bug in mine.
Good work.

**Pull request merged**
