### PR TITLE
 URL-encode IDs in delete executables

### PR DESCRIPTION
**Pull request by missingfaktor**
Backported from `master`.

### CODE REVIEW

**Comment by missingfaktor** [comment]
@sksamuel Sorry to trouble you again. Encountered another bug a while ago. This PR contains a fix. If all looks good, could you please merge and release? Thanks so much in advance!

**Comment by sksamuel** [comment]
5.4.17

**Comment by missingfaktor** [comment]
Thanks so much!

**Comment by missingfaktor** [comment]
Getting this error:

```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.sksamuel.elastic4s#elastic4s-core_2.12;5.4.17: not found
[warn] 	:: com.sksamuel.elastic4s#elastic4s-http_2.12;5.4.17: not found
[warn] 	:: com.sksamuel.elastic4s#elastic4s-circe_2.12;5.4.17: not found
[warn] 	:: com.sksamuel.elastic4s#elastic4s-testkit_2.12;5.4.17: not found
[warn] 	:: com.sksamuel.elastic4s#elastic4s-embedded_2.12;5.4.17: not found
[warn] 	:::::::::::::::::::::::::::::::::::::::
```

Also in the README, 5.4.16 is still listed as the latest 5.4.x release.

**Comment by sksamuel** [comment]
Sometimes it takes 10 minutes or so to appear
It's there now
*http://repo1.maven.org/maven2/com/sksamuel/elastic4s/elastic4s-http_2.12/5.4.17/
<http://repo1.maven.org/maven2/com/sksamuel/elastic4s/elastic4s-http_2.12/5.4.17/>*

**Comment by missingfaktor** [comment]
Ah. Thank you!

**Pull request merged**
