### PR TITLE
Fix phrase suggestion highlights

### PR DESCRIPTION
**Pull request by Dbzman**
A new release after merge would be nice 😋

### CODE REVIEW

**Comment by sksamuel** [comment]
I can't do 3 release a day :)
I've just done 6.3.2 for you after your last PR. I'll do 6.3.3 next week.

**Comment by Dbzman** [comment]
I can understand that. Is there a way to use the current snapshot/latest master then? (I couldn't find it)
Probably it makes sense to have that snapshots published on commit. What do you think? :)

**Comment by sksamuel** [comment]
I need to set travis to do snapshot release on each commit. I'll look into it.

**Comment by Dbzman** [comment]
Sounds cool, thanks! :)

**Pull request merged**
