### PR TITLE
Exposed 'sort' in SearchHit. Used for search_after.

### PR DESCRIPTION
**Pull request by ryan-martin-axiell**

### CODE REVIEW

**Comment by sksamuel** [comment]
:+1:

**Comment by knight76** [comment]
In 6.1.3, I could not find sort field from search response. 
I would try to suggest on this, but @ryan-martin-axiell sent pull request. 
Good Job! Thanks. 
👍

**Comment by knight76** [comment]
@sksamuel 
When is 6.1.4 release date? I hope to use it.

**Comment by sksamuel** [comment]
Some PR has fucked up the build and when I try to release it has duplicated scm tags. So I'll need to figure that out first.

**Comment by sksamuel** [comment]
@knight76 6.1.4 is released.

**Pull request merged**
