### PR TITLE
ENTELLECT-411 Fix preference bug in 6.2.x

### PR DESCRIPTION
**Pull request by steve-e**
#1398 

I extracted a RichSearchDefinition class to enable unit testing. The integration test I added in CommonQueryTest doesn't really test the preference functionality, but it does at least fail without the fix. To really test the preference functionality I think you'd need a multi node cluster

### CODE REVIEW

**Comment by sksamuel** [comment]
:+1: 

Would be great to have a PR for this to master as well.

**Comment by steve-e** [comment]
I will try and get a pr for master made this week

**Comment by Dbzman** [comment]
Any news about this? We have the same issue with the latest release (6.3.0) and it would be cool to have it merged to master. :)

**Comment by sksamuel** [comment]
You mean the latest release of elasticsearch?

**Comment by Dbzman** [comment]
Sorry, I mean elastic4s. We use 6.2.9^^
Seems that just a new release is necessary. :)

**Pull request merged**
