### PR TITLE
artifact for AWS suggestion

### PR DESCRIPTION
**Pull request by kimxogus**
A suggestion for AWS ES support.
- Set artifact postfix `aws`
- Set elasticsearch version to 5.3
- Added AWSHttpClient

I recommend to make a new release branch for aws if this is accpeted

### CODE REVIEW

**Comment by sksamuel** [comment]
Github is showing 25 commits to review. Can you squash into a single commit ?

**Comment by kimxogus** [comment]
I had some trouble in squasing, so I just made a new commit and force updated.

**Comment by sksamuel** [comment]
Excellent :+1:

**Comment by sksamuel** [comment]
Would be awesome if we could have this for master branch too.

**Comment by kimxogus** [comment]
Uh.. this will change entire project name to `elastic4s` to `elastic4s-aws`. Is that ok?
Also aws is not supporting es 6.0 for now.

**Comment by sksamuel** [comment]
I've reverted it after I saw that!

**Comment by kimxogus** [comment]
I recommend to create new branch for aws

**Pull request merged**
