### PR TITLE
backport of #1922 to 6.7.x branch

### LINKED ISSUE #1922: The PublishActor should try to clearScroll on postStop
Currently, the `PublisherActor` only clears the scroll id when there's an empty message (https://github.com/sksamuel/elastic4s/blob/master/elastic4s-http-streams/src/main/scala/com/sksamuel/elastic4s/streams/ScrollPublisher.scala#L161)

Note that there are cases where the actor dies without clearing the `scrollId`, which can lead to a ton of open contexts (e.g. an overloaded node can start returning timeouts, which would kill the actor without removing the scrolling context).

I think that the actor should always try to call the `clearScroll` on `onStop`, as a best effort.

### PR DESCRIPTION
**Pull request by brunoballekens**
Backport of PR#1930 to 6.7.x branch

fixes #1922 and #1799 
Could you also make a new release of the 6.7 branch ? Thanks

### CODE REVIEW

**Comment by francisdb** [comment]
+1 for a release

**Comment by brunoballekens** [comment]
Hi @sksamuel would it be possible to create a 6.7.x release in the near future (next two weeks) ?

**Comment by sksamuel** [comment]
I had done a bunch of 6.x released this past week but must have forgotten 6.7 sorry.  I will release now.

**Comment by sksamuel** [comment]
6.7.6 has been released.

**Comment by brunoballekens** [comment]
Super, thank you !

**Pull request merged**
