### PR TITLE
Restore missing 1.7.x commits

### PR DESCRIPTION
**Pull request by longcao**
This PR addresses https://github.com/sksamuel/elastic4s/issues/510, in which some commits from 1.7.1 were missing from future versions.

I accomplished this with a git merge onto `release/1.7.x`, specifically:

`git merge --strategy recursive -X patience 1.7.1` (although I don't think the `patience` really did anything different, it was suggested for branches that differ "wildly", according to http://git-scm.com/docs/merge-strategies).

I also had to manually resolve some merge conflicts in the process, favoring changes that:

a) showed up in later versions
b) were later version numbers
c) or were required to compile

I wasn't able to get tests to run successfully on my local environment, but it appears that tests are broken for the `release/1.7.x` branch anyways on [the Travis build](https://travis-ci.org/sksamuel/elastic4s/builds/106156660).

Please let me know if there's anything else I can do, looking forward to a fresh new release if not.

### CODE REVIEW

**Comment by longcao** [comment]
@sksamuel is there anything I can do to get this pulled across the finish line?

**Comment by sksamuel** [comment]
@longcao travis is reporting compilation errors, if we can fix that I can release

**Comment by longcao** [comment]
@sksamuel I reverted https://github.com/sksamuel/elastic4s/commit/ed248cabe3e29ac83aad057ddee8396ba05c820a since that seemed to be causing the test compilation errors (Travis build is now green) but I don't know the context of removing it in the first place, let me know if this works for you!

**Comment by sksamuel** [comment]
:+1:

**Comment by sksamuel** [comment]
1.7.6 is on maven central

**Comment by longcao** [comment]
Thanks!

**Pull request merged**
