### PR TITLE
Build documentation with sbt-microsite

### PR DESCRIPTION
**Pull request by muuki88**
This pull requests moves the `guide` folder content  to a separate sbt module `docs`,
which builds the documentation and generates a nice looking site.

Also the scaladoc is generated with `sbt-unidoc` into a single API.

- [x] no logo, the microsite default logo is being used. Maybe not a blocker
- [ ] documentation is not yet compiled, but simply rendered
- [x] integrate in the release process

# Screenshots

elastics4-home

elastic4s-docs

### CODE REVIEW

**Comment by sksamuel** [comment]
Does this mean every time I make a documentation change I have to run some step to publish? Or is it all automatic?

**Comment by muuki88** [comment]
> Does this mean every time I make a documentation change I have to run some step to publish? Or is it all automatic?

I can integrate it into the release process. So every time a release is made with `sbt release` the github page is updated.

**Comment by muuki88** [comment]
Do you need any help for the initial setup of the site? Basically you have to follow
[the ghpages sbt plugin documentation](https://github.com/sbt/sbt-ghpages#initializing-the-gh-pages-branch). For the first time you have to create the necessary ghpages branch.

**Comment by sksamuel** [comment]
I've created the branch but I can't seem to get `sbt ghpagesPushSite` to work.

**Comment by muuki88** [comment]
Publishing the site should work with
```
sbt docs/publishMicrosite
```

**Comment by sksamuel** [comment]
What does the `docs/` bit mean in the task?

**Comment by sksamuel** [comment]
http://sksamuel.github.io/elastic4s/

**Comment by muuki88** [comment]
`docs` is a sbt submodule that is responsible for building the docs :)

**Comment by sksamuel** [comment]
Ok, not sure what an sbt submodule is. Maybe I don't want to know :)

**Comment by muuki88** [comment]
Are you at the Scaladays in Copenhagen? Or if you are in munich some times, you could come over, if you like ;) SBT modules are like maven multi-pom builds :P

**Comment by sksamuel** [comment]
I don't like flying so I don't travel much :)

**Comment by muuki88** [comment]
I prefer trains as well. However I like meeting the people behind awesome projects,
so I battle my own laziness :) You are in London, right?

**Pull request merged**
