### PR TITLE
Support script in Reindex api

### PR DESCRIPTION
**Pull request by TrustNoOne**
just that

cheers

### CODE REVIEW

**Comment by sksamuel** [comment]
Thanks

**Comment by TrustNoOne** [comment]
@sksamuel hi, any time frame for releasing this in next 6.2.x?

**Comment by sksamuel** [comment]
Tonight

On 24 Apr 2018 11:03 am, "Giovanni Caporaletti" <notifications@github.com>
wrote:

@sksamuel <https://github.com/sksamuel> hi, any time frame for releasing
this in next 6.2.x?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/sksamuel/elastic4s/pull/1327#issuecomment-383876405>,
or mute the thread

**Comment by TrustNoOne** [comment]
it's on master but it's not on the release branch :(

**Comment by sksamuel** [comment]
Someone will need to do a PR to 6.2.x branch and then I'll do a release.

**Comment by TrustNoOne** [comment]
I thought you were merging back changes, sorry, I'll open a PR right away

**Comment by sksamuel** [comment]
I merge from 6.2 into master, I don't tend to merge from master back unless someone wants it and does a PR.

**Comment by TrustNoOne** [comment]
ok good to know! 👍

**Comment by sksamuel** [comment]
I really want elastic to release 7.0 so I can do a release of master.

**Pull request merged**
