### PR TITLE
Reindex executables

### LINKED ISSUE #997: Reindex missing on HTTP client
```
could not find implicit value for parameter exec: com.sksamuel.elastic4s.http.HttpExecutable[com.sksamuel.elastic4s.reindex.ReindexDefinition,U]
```

### PR DESCRIPTION
**Pull request by kimxogus**
Added `ReindexExecutables` and `ReindexContentBuilder`

this will fix #997

### CODE REVIEW

**Comment by kimxogus** [comment]
Also this pr extends #1074

**Comment by sksamuel** [comment]
awesome

**Comment by sksamuel** [comment]
What do you think about adding the reindex operations to master as well ?

**Comment by kimxogus** [comment]
Sure!

**Pull request merged**
