### PR TITLE
Implement slice api for scrolling

### PR DESCRIPTION
**Pull request by hensg**
Slice API for release 5.4.x

### CODE REVIEW

**Comment by hensg** [comment]
:dancer:

**Comment by hensg** [comment]
Do you know when a version with this implementation will be released? =)

**Comment by sksamuel** [comment]
I'll do it overnight, my internet is not fast enough to upload all the jars while I'm using it as well. So I'll set it going before bed. If I have't had too much to drink and forget ;)

**Comment by sksamuel** [comment]
5.4.13 is released now.

**Pull request merged**
