### PR TITLE
Solved "stopwords_list" build fail and added Apostrophe filter

### PR DESCRIPTION
**Pull request by apanimesh061**
Build for the fork passed.

### CODE REVIEW

**Comment by sksamuel** [comment]
You deleted teh update sql test file ?

**Comment by apanimesh061** [comment]
I removed it from the project as SnapShotDsl and UpdateSql were causing the build to fail. I have their copies with me. You want me to commit them as well?

**Comment by sksamuel** [comment]
You commit them and I'll fix them.

**Comment by apanimesh061** [comment]
I have committed the two files. See if its okay.

**Pull request merged**
