### PR TITLE
Add '_parent' to SearchHit

### PR DESCRIPTION
**Pull request by kutchar**
`_parent` field is missing in 5.4.x but exists in 6.x

### CODE REVIEW

**Comment by kutchar** [comment]
@sksamuel Please let me know when you can merge this

**Comment by sksamuel** [comment]
Merged

**Comment by kutchar** [comment]
Would this be released as `5.4.9`?

**Comment by sksamuel** [comment]
Can do.

On 29 Jul 2017 7:29 am, "Drew Kutcharian" <notifications@github.com> wrote:

Would this be released as 5.4.9?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/sksamuel/elastic4s/pull/1005#issuecomment-318808350>,
or mute the thread

**Comment by kutchar** [comment]
Actually wait. There are a few more issues which I'll be making PRs for in the next couple of days.

**Comment by sksamuel** [comment]
Ok

**Pull request merged**
