### PR TITLE
scalafmtCheck on CI

### PR DESCRIPTION
**Pull request by joan38**

### CODE REVIEW

**Comment by sksamuel** [comment]
This PR doesn't build cleanly, so I've reverted it in https://github.com/sksamuel/elastic4s/pull/1275

**Comment by joan38** [comment]
I forgot to apply the formatting.
Fixed by https://github.com/sksamuel/elastic4s/pull/1277

**Comment by sksamuel** [comment]
Ironic that the formatting pr failed on formatting :)

**Comment by joan38** [comment]
Ahah

**Pull request merged**
