### PR TITLE
Fixing Issue 2400 - Adding zio-json support

### PR DESCRIPTION
**Pull request by remiguittaut**
Issue 2400.

Adding type different json type class instances for zio-json.

Some test are not passing, but it is unrelated to this PR, as they are also failing in master.

### CODE REVIEW

**Comment by sksamuel** [comment]
Master is green right now, where did you see them failing?

**Comment by remiguittaut** [comment]
Maybe I did something wrong, I just pulled master and `sbt test`. At least the small modification i did should not influence the other tests in any way.

**Comment by remiguittaut** [comment]
Ha and I have a typo in the `@implicitNoFound` message, I will fix that.

**Comment by sksamuel** [comment]
👍🏼

**Pull request merged**
